# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  moveapk:
    runs-on: windows-2019
    
    steps:
    - run: |
        del Files\FinanceApp.apk
        move /y app\build\outputs\apk\debug\app-debug.apk Files\FinanceApp.apk
        
      
