name: Manual workflow
on:
  push:
    branches: master
  workflow_dispatch:

jobs:
  copyapk:
    runs-on: windows-2019
    defaults:
      run:
        shell: cmd
    
    env:
      USER_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
      USER_NAME: "github-actions[bot]"
    
    steps:
    - uses: actions/checkout@v2
    
    - name: git config
      run: |
        git config --local user.email "%USER_EMAIL%"
        git config --local user.name "%USER_NAME%"
        git checkout "${{ github.ref }}"
    
    - name: copy
      run: |
        copy /y app\build\outputs\apk\debug\app-debug.apk Files\FinanceApp.apk
        
        git add .
        git commit -m ".apk copied"
